### ISSUE TITLE
Traveler Login

### ISSUE THREAD

**Issue by josh-everett01** [josh-everett01/travel_tracker#3]
## Description:
As a user on the travel tracker website, when I visit the root path, I see a login page with a well-styled form that has username and password fields. When I enter the credentials: 

```
username: traveler50 (where 50 is the ID of the user)
password: travel2020
```

I should see the following behavior:
* The page should clear
* an H1 tag should be rendered with the traveler ID

#### Sad Path:
When I enter the credentials: 

```
username: traveler50 (where 50 is the ID of the user)
password: travel2021
```

I should see the following behavior:
* An alert should render "Incorrect Login!"
* The form fields should be cleared

When I enter the credentials: 

```
username: traveler650 (where 650 is the ID of a user not in the API database)
password: travel2020
```

I should see the following behavior:
* An alert should render "Invalid Traveler Login!"
* The form fields should be cleared

### Checks:
- [x] All story criteria has been met
- [x] All commits adhere to agreed upon structure
- [x] All styling is satisfactory for both mobile and PC

##### Notes:
All branches in this project will be named as follows:
```
issue_[issue number]
```

**Comment by Mycobee** [comment]
@josh-everett01 don't forget to open a PR for this issue.  I noticed you pushed a branch, but did not open a pull request.

I think you will have merge conflicts concerning this whole process, and it might be a large PITA.  You might need to create a new branch off of master (checkout master, pull origin master, checkout [new_branch]) and cherry pick the commits off of the issue_2 branch.  

Definitely not the most simple way to get introduced to git, but because you made your issue_2 branch off of your issue_1 branch, you will have to do some stuff to make it all work :+1: 

good luck, holler if you get stuck

**Comment by josh-everett01** [comment]
I was able to do a pull request for it and it shows one for each branch now. If my code looks correct after I pulled is all good?
